# -*- coding: utf-8 -*-
"""Jetson LoRa Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHt1o1sZFHWDj2XO78SSuyJTXkBUZwp4
"""

import serial
import time
import threading
import sys

# CONFIGURATION
# D14/D15 on Jetson Nano header corresponds to /dev/ttyTHS1
SERIAL_PORT = '/dev/ttyTHS1'
BAUD_RATE = 115200

# LoRa Configuration matches your C++ sketch
# We set this device to Address 2 so it can talk to your Arduino (Address 1)
LORA_ADDRESS = "2"
LORA_NETWORK_ID = "18"
LORA_BAND = "915000000"
LORA_PARAMETERS = "11,9,4,24"

class LoRaTransceiver:
    def __init__(self, port, baud):
        try:
            self.ser = serial.Serial(
                port,
                baud,
                timeout=1
            )
            print(f"Opened {port} at {baud} baud.")
        except serial.SerialException as e:
            print(f"Error opening serial port: {e}")
            print("Did you stop nvgetty? (sudo systemctl stop nvgetty)")
            sys.exit(1)

        self.running = True
        self.configure_module()

    def send_at_command(self, command):
        """Sends an AT command and waits a brief moment."""
        # Reyax modules expect \r\n at the end of commands
        full_command = f"{command}\r\n"
        self.ser.write(full_command.encode('utf-8'))
        time.sleep(0.03) # Small delay to allow module to process

    def configure_module(self):
        """Sets up the Reyax module with specific parameters."""
        print("Initializing LoRa Module...")

        # Test connection
        self.send_at_command("AT")

        # Set Configuration
        self.send_at_command(f"AT+ADDRESS={LORA_ADDRESS}")
        self.send_at_command(f"AT+NETWORKID={LORA_NETWORK_ID}")
        self.send_at_command(f"AT+BAND={LORA_BAND}")
        self.send_at_command(f"AT+PARAMETER={LORA_PARAMETERS}")

        print(f"Setup Complete. Local Address: {LORA_ADDRESS}, Network: {LORA_NETWORK_ID}")
        print("Format to send: <message>,<target_address>")
        print("Example: Hello,1")

    def receive_loop(self):
        """Thread function to handle incoming data from LoRa."""
        while self.running:
            try:
                if self.ser.in_waiting > 0:
                    # Read line, decode, and strip whitespace
                    line = self.ser.readline().decode('utf-8', errors='ignore').strip()

                    if not line:
                        continue

                    # Parse Received Message
                    # Format: +RCV=<Address>,<Length>,<Data>,<RSSI>,<SNR>
                    if line.startswith("+RCV="):
                        parts = line.split(',')
                        if len(parts) >= 3:
                            sender_addr = parts[0].split('=')[1]
                            msg_len = parts[1]
                            content = parts[2]
                            rssi = parts[3] if len(parts) > 3 else "N/A"

                            print(f"\n[RECEIVED] From: {sender_addr} | Msg: {content} | RSSI: {rssi}")
                            print("Enter command: ", end='', flush=True) # Restore prompt

                    # Handle Command Responses (OK, ERR)
                    elif "+ERR" in line:
                         print(f"\n[MODULE ERROR] {line}")
                    elif "OK" in line:
                        pass # Ignore standard OK responses to keep console clean
                    else:
                        # Print other unexpected debug data
                        print(f"\n[MODULE DEBUG] {line}")

            except OSError:
                print("Serial port error.")
                self.running = False
            except Exception as e:
                print(f"Error in receive loop: {e}")

    def send_message(self, message, address):
        """Formats and sends the AT+SEND command."""
        length = len(message)
        cmd = f"AT+SEND={address},{length},{message}"

        print(f"Sending to {address}: {message}")
        self.send_at_command(cmd)

    def main_loop(self):
        """Main input loop."""
        # Start the receiver thread
        rx_thread = threading.Thread(target=self.receive_loop)
        rx_thread.daemon = True
        rx_thread.start()

        time.sleep(1) # Wait for config to settle

        print("\n--- Ready ---")

        while self.running:
            try:
                user_input = input("Enter command (<msg>,<addr>): ")

                if not user_input:
                    continue

                if user_input.lower() == 'exit':
                    break

                if ',' in user_input:
                    # Split only on the last comma to allow commas in the message
                    # But the format requested is specific, so we'll do standard split
                    parts = user_input.rsplit(',', 1)
                    if len(parts) == 2:
                        msg = parts[0].strip()
                        addr = parts[1].strip()
                        self.send_message(msg, addr)
                    else:
                        print("Invalid format. Use: message,address")
                else:
                    print("Invalid format. Missing address. Use: message,address")

            except KeyboardInterrupt:
                print("\nExiting...")
                self.running = False
                break

        self.ser.close()

if __name__ == "__main__":
    lora = LoRaTransceiver(SERIAL_PORT, BAUD_RATE)
    lora.main_loop()
